name: Deploy-Prod

on: 
  workflow_dispatch:
    inputs:
        sha:
          description: 'Commit ID'
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ inputs.sha }}"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: out/
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS_PROD }}
          REMOTE_USER: ec2-user
          TARGET: ${{ secrets.TARGET_DIR }}/out
